name: Newapp  # <--- මෙතන නම වෙනස් කරන්න (Folder එකේ නම දාන්න)
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code quality rules
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Assets දානකොට මේ යට පේළි වල ඉස්සරහ තියෙන # අයින් කරන්න
  # assets:
  #   - assets/images/
  assets:
    - assets/images/